---
title: 'DGP Variations'
output:
  pdf_document: default
  bookdown::html_document2: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(dplyr, furrr,here,tictoc, gt, ggplot2, gridExtra, knitr,
               stringr, tidyr)
source(here("r_code/factor_dgp.R"))
source(here("r_code/seed_metrics.R"))
plan(multiprocess, workers=availableCores()-1)
```


## For Loop Over DGPs

```{r dgp-param-list, echo=FALSE}

aa_dgp_params<-list(
  "aa_high_acf"=list(date_start="2010-01-01",
       first_treat="2017-07-01",
       date_end="2020-01-01",
       num_entries=200,
       prop_treated=0.25,
       treat_impact_sd = 0, 
       treat_impact_mean = 0, 
       rho=0.9,
       num_factors=4,
       rescale_y_mean = 2.5e3,
       cov_overlap_scale = 0,
       seed=42),
  "aa_high_acf_loading_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.9,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    cov_overlap_scale = 0,
    intercept_scale = 0,
    loading_scale = 0.75,
    seed=42
  ),
  "aa_low_acf"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.1,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    cov_overlap_scale = 0,
    seed=42
  ),
  "aa_low_acf_sel_covariate_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.1,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    selection="observables",
    cov_overlap_scale = 0.75,
    loading_scale = 0,
    seed=42
  ),
  "aa_noisy_factors"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.9,
    num_factors=6,
    rescale_y_mean = 2.5e3,
    cov_overlap_scale = 0,
    loading_scale = 0,
    seed=42
  ),
  
  "aa_noisy_factors_load_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.9,
    num_factors=6,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42
  ),
  
  "aa_noisy_factors_lowacf"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.2,
    num_factors=6,
    rescale_y_mean = 2.5e3,
    cov_overlap_scale = 0,
    loading_scale = 0,
    seed=42
  ),
  
  "aa_noisy_factors_load_shift_lowacf"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0, 
    rho=0.2,
    num_factors=6,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42
  )
)

ab_dgp_params<-list(
  "ab_no_het"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    cov_overlap_scale = 0,
    seed=42 ),
  "ab_no_het_loading_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42 ),
  "ab_impact_het_loading_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0.1, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42 
  ),
  "ab_decay_het_loading_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0.1,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42 
  ),
  "ab_decay_impact_het_loading_shift"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0.1,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0.75,
    seed=42 
  ),
  "ab_impact_het"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0.1, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0,
    seed=42 
  ),
  "ab_decay_het"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0.1,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0,
    seed=42 
  ),
  "ab_decay_impact_het"=list(
    date_start="2010-01-01",
    first_treat="2017-07-01",
    date_end="2020-01-01",
    num_entries=200,
    prop_treated=0.25,
    treat_impact_sd = 0, 
    treat_impact_mean = 0.1,
    treat_decay_mean=0.7,
    treat_decay_sd=0.1,
    rho=0.75,
    num_factors=4,
    rescale_y_mean = 2.5e3,
    loading_scale = 0,
    seed=42 
  )
)

all_dgp_params=c(ab_dgp_params, aa_dgp_params)

```

```{r dgp-loop, echo=FALSE}

for_gt=list()
dataset_names=setdiff(list.files(here::here("Data", "Variations")), "Old")
for(data_i in seq_len(length(dataset_names))){
  load(here::here("Data", "Variations",dataset_names[data_i] ))

  
  data_name=stringr::str_remove(tolower(dataset_names[data_i]), ".rdata")
  print(data_name)
    #Create long form data for each metric
  coverage_tib=gsynth_coverage %>% 
      dplyr::mutate( method="gsynth") %>%
      dplyr::bind_rows(
          scdid_coverage %>% 
              dplyr::mutate( method="scdid"))%>%
      dplyr::bind_rows(
          mc_coverage %>% 
              dplyr::mutate( method="mc"))%>%
    dplyr::bind_rows(
          causalimpact_coverage %>% 
              dplyr::mutate(method="causalimp")) %>%
    dplyr::bind_rows(
          ensemble_coverage %>% 
              dplyr::mutate( method="ensemble"))%>%
    dplyr::mutate(metric="coverage", metric_value=coverage_abs)%>%
    dplyr::select(post_period_t,metric, method, metric_value)
  
  
  
  rmse_tib=gsynth_overall_metrics %>% 
    dplyr::mutate( method="gsynth") %>%
      dplyr::bind_rows(
          scdid_overall_metrics %>% 
              dplyr::mutate(method="scdid"))%>%
      dplyr::bind_rows(
          mc_overall_metrics %>% 
              dplyr::mutate( method="mc"))%>%
    dplyr::bind_rows(
          causalimpact_overall_metrics %>% 
              dplyr::mutate( method="causalimp"))%>%
    dplyr::bind_rows(
          ensemble_overall_metrics %>% 
              dplyr::mutate( method="ensemble"))%>%
    dplyr::mutate(metric="rmse", metric_value=jackknife_rmse)%>%
    dplyr::select(post_period_t,metric, method, metric_value)
  
  bias_tib=gsynth_bias %>%
    dplyr::mutate( method="gsynth") %>%
      dplyr::bind_rows(
          scdid_bias %>%
              dplyr::mutate( method="scdid"))%>%
      dplyr::bind_rows(
          mc_bias %>%
              dplyr::mutate( method="mc"))%>%
      dplyr::bind_rows(
          causalimpact_bias %>%
              dplyr::mutate(method="causalimp"))%>%
    dplyr::bind_rows(
          ensemble_bias %>%
              dplyr::mutate( method="ensemble"))%>%
    dplyr::mutate(metric="bias", metric_value=jackknife_abs_bias) %>%
    dplyr::select(post_period_t, metric,metric_value, method)
  
  #combine the metrics into one long form tibble, #spread the long form to wide
  for_gt[[data_i]]=metrics_tib=coverage_tib %>%
    dplyr::bind_rows(rmse_tib) %>%
    dplyr::bind_rows(bias_tib) %>%
    tidyr::pivot_wider(names_from = c( method ), values_from=metric_value)
  
}


make_tables<-function(tib_to_gt_data, datalist, ignore_indiv=F){
  load(here::here("Data", "Variations",datalist ))
  
  data_name=stringr::str_remove(tolower(datalist), ".rdata")
  #print(data_name)
  #print(all_dgp_params[[match(data_name,names(all_dgp_params))]])
  
    gridExtra::grid.arrange(
    gsynth_bias_plot,
    scdid_bias_plot,
    mc_bias_plot,
    causalimpact_bias_plot,
    ensemble_bias_plot,
    nrow = 3,
    top = paste("Bias by Method: ", data_name,sep=""),
    bottom = "Notes:")
    
    random_data=sample(1:n_seeds,1)
    if(!ignore_indiv){
      indiv_cf_plots_gsynth=lapply(plot_individual_cf(gsynth_est[[random_data]])[c(1,2)],
                                 function(x){
                                   x+ggplot2::labs(caption="Gsynth")
                                 })
      indiv_cf_plots_scdid=lapply(plot_individual_cf(scdid_est[[random_data]])[c(1,2)],
                                  function(x){
                                     x+ggplot2::labs(caption="SCDID")
                                   })
      indiv_cf_plots_mc=lapply(plot_individual_cf(mc_est[[random_data]])[c(1,2)],
                               function(x){
                                     x+ggplot2::labs(caption="MC")
                                   })
      indiv_cf_plots_causalimpact=lapply(
        plot_individual_cf(causalimpact_est[[random_data]])[c(1,2)],
        function(x){ x+ggplot2::labs(caption="Causal Impact") })
      indiv_cf_plots_ensemble=lapply(
        plot_individual_cf(ensemble_est[[random_data]])[c(1,2)],
        function(x){ x+ggplot2::labs(caption="Ensemble")  })
      
      indiv_cf_combined=c(
        indiv_cf_plots_gsynth,indiv_cf_plots_scdid,indiv_cf_plots_mc,
        indiv_cf_plots_causalimpact ,indiv_cf_plots_ensemble
    )
    
    lapply(indiv_cf_combined,print)
    }

    
    gridExtra::grid.arrange(tsfeature_pc_by_treatment_plot(formatted_data[[random_data]])+
      ggplot2::labs(caption = data_name), nrow=1)
    
    print(tsfeature_by_treat_df(formatted_data[[random_data]]) %>% 
            dplyr::select(-c(".y.", group1, group2)))
    
  
  return(tib_to_gt_data %>%
    gt::gt(rowname_col = "post_period_t", groupname_col = "metric") %>%
      gt::tab_header(
          title = gt::md("Metrics by Method"),
          subtitle = gt::md(data_name)
      ) %>%
      gt::tab_source_note(gt::md("Notes:")) %>%
    gt::tab_stubhead(label = "Method") %>%
    gt::fmt_number(columns=dplyr::everything(), decimals = 3))
  
  

}
#won't print properly in lapply
make_tables(for_gt[[1]], dataset_names[[1]])
make_tables(for_gt[[2]], dataset_names[[2]])
make_tables(for_gt[[3]], dataset_names[[3]])
make_tables(for_gt[[4]], dataset_names[[4]])
make_tables(for_gt[[5]], dataset_names[[5]])
make_tables(for_gt[[6]], dataset_names[[6]])
make_tables(for_gt[[7]], dataset_names[[7]])
make_tables(for_gt[[8]], dataset_names[[8]])
make_tables(for_gt[[9]], dataset_names[[9]])
make_tables(for_gt[[10]], dataset_names[[10]])
make_tables(for_gt[[11]], dataset_names[[11]])
make_tables(for_gt[[12]], dataset_names[[12]])
make_tables(for_gt[[13]], dataset_names[[13]])
make_tables(for_gt[[14]], dataset_names[[14]])
make_tables(for_gt[[15]], dataset_names[[15]])
make_tables(for_gt[[16]], dataset_names[[16]])

```


